import {
  ACK_RESULT,
  DEFAULT_BUTTON_REMAP_PROFILE,
  type ControllerProfileSettings
} from '../../shared/protocol';
import { DEFAULT_TOUCHPAD_SETTINGS } from '../../shared/touchpad-gestures';
import type {
  BridgeDiagnostics,
  BridgeSnapshot,
  CompanionSettings
} from '../../shared/types';

export const DEFAULT_MOCK_CONTROLLER_SETTINGS: ControllerProfileSettings = {
  leftStickRadialDeadzonePercent: 0,
  rightStickRadialDeadzonePercent: 0,
  hapticsEnabled: true,
  hapticsGainPercent: 100,
  feedbackBoostEnabled: false,
  classicRumbleEnabled: true,
  classicRumbleGainPercent: 100,
  classicRumbleV1Enabled: false,
  adaptiveTriggersEnabled: true,
  triggerEffectIntensityPercent: 100,
  triggerTestMode: 'feedback',
  speakerEnabled: true,
  speakerVolumePercent: 100,
  micVolumePercent: 100,
  micMuted: false,
  audioReactiveHapticsEnabled: false,
  audioReactiveHapticsSource: 'system-audio',
  audioReactiveHapticsMode: 'mix',
  audioReactiveHapticsGainPercent: 100,
  audioReactiveHapticsBassFocus: 'balanced',
  audioReactiveHapticsResponse: 'balanced',
  audioReactiveHapticsAttack: 'balanced',
  audioReactiveHapticsRelease: 'balanced',
  lightbarEnabled: true,
  lightbarColor: '#0066FF',
  lightbarBrightnessPercent: 100,
  lightbarOverrideEnabled: false,
  muteButtonMode: 'normal',
  muteKeyboardUsage: 0,
  muteKeyboardModifiers: 0,
  muteKeyboardBehavior: 'tap',
  muteKeyboardChordStarterEnabled: false,
  edgeProfileSwitchingBlocked: false,
  sleepKeybindEnabled: false,
  speakerVolumeShortcutEnabled: false,
  pollingRateMode: '1000',
  hostPersonaMode: 'dualsense',
  duplexMicEnabled: false,
  controllerPowerSavingEnabled: false
};

export const DEFAULT_MOCK_SETTINGS: CompanionSettings = {
  selectedPresetId: 'balanced',
  uiScalePercent: 100,
  uiThemePreset: 'dark',
  launchAtStartupEnabled: false,
  showBatteryPercentTrayIcon: false,
  kitsuneInputPromotionDismissed: false,
  firmwareLogDirectory: null,
  leftStickRadialDeadzonePercent: 0,
  rightStickRadialDeadzonePercent: 0,
  hapticsEnabled: true,
  hapticsGainPercent: 100,
  feedbackBoostEnabled: false,
  hapticsBufferLength: 64,
  audioInterleaveMaxConsecutiveAudioSends: 4,
  audioInterleaveStateMaxAgeUs: 10000,
  classicRumbleEnabled: true,
  classicRumbleGainPercent: 100,
  classicRumbleV1Enabled: false,
  adaptiveTriggersEnabled: true,
  triggerEffectIntensityPercent: 100,
  triggerTestMode: 'feedback',
  speakerEnabled: true,
  speakerVolumePercent: 100,
  speakerGainLevel: 4,
  selectedBridgePath: 'usb:mock-pico-01',
  bridgeIdentities: {},
  controllerBindings: {},
  micVolumePercent: 100,
  micMuted: false,
  audioReactiveHapticsEnabled: false,
  audioReactiveHapticsSource: 'system-audio',
  audioReactiveHapticsMode: 'mix',
  audioReactiveHapticsGainPercent: 100,
  audioReactiveHapticsBassFocus: 'balanced',
  audioReactiveHapticsResponse: 'balanced',
  audioReactiveHapticsAttack: 'balanced',
  audioReactiveHapticsRelease: 'balanced',
  lightbarEnabled: true,
  lightbarColor: '#0066FF',
  lightbarBrightnessPercent: 100,
  lightbarOverrideEnabled: false,
  lightbarRestoreEnabled: true,
  muteButtonMode: 'normal',
  muteKeyboardUsage: 0,
  muteKeyboardModifiers: 0,
  muteKeyboardBehavior: 'tap',
  muteKeyboardChordStarterEnabled: false,
  edgeProfileSwitchingBlocked: false,
  ledEnabled: true,
  playerLedEnabled: true,
  idleDisconnectEnabled: false,
  idleDisconnectTimeoutMinutes: 15,
  usbSuspendDisconnectEnabled: true,
  wakeOnConnectEnabled: true,
  sleepKeybindEnabled: false,
  speakerVolumeShortcutEnabled: false,
  pollingRateMode: '1000',
  hostPersonaMode: 'dualsense',
  notifyControllerConnection: true,
  notifyLowBattery: true,
  duplexMicEnabled: false,
  controllerPowerSavingEnabled: false,
  selectedControllerProfileId: 'default',
  controllerProfiles: [
    {
      id: 'default',
      name: 'Standard DualSense',
      settings: { ...DEFAULT_MOCK_CONTROLLER_SETTINGS }
    }
  ],
  selectedButtonRemappingProfileId: 'default',
  buttonRemappingProfiles: [
    {
      id: 'default',
      name: 'Default 1:1',
      mappings: { ...DEFAULT_BUTTON_REMAP_PROFILE.mappings }
    }
  ],
  buttonRemappingDraft: { ...DEFAULT_BUTTON_REMAP_PROFILE.mappings },
  chordFunctions: [],
  chordAssignments: [],
  touchpadSettings: { ...DEFAULT_TOUCHPAD_SETTINGS },
  turboSettings: {
    enabled: false,
    speedCps: 8,
    humanize: true,
    buttonsMask: 0
  },
  gameProfileAutoSwitchEnabled: false,
  gameProfiles: []
};

export const DEFAULT_MOCK_DIAGNOSTICS: BridgeDiagnostics = {
  hidPath: 'usb:mock-pico-01',
  protocolVersion: '1.7.1',
  uptimeSeconds: 3600,
  settingsRevision: 1,
  lastAck: {
    commandId: 0,
    commandSequence: 1,
    resultCode: ACK_RESULT.OK,
    detailCode: 0,
    settingsRevision: 1,
    uptimeSeconds: 3600,
    protocolVersion: '1.7.1'
  },
  lastError: null,
  firmwareUpdateAvailable: null,
  lastPollAt: Date.now(),
  rawDevices: [],
  deviceIdentity: {
    schemaVersion: 1,
    bridgeId: 'pico-01',
    controllerConnected: true,
    pairingActive: false,
    addressKnown: true,
    bluetoothAddress: 'AA:BB:CC:DD:EE:FF',
    linkKeyKnown: true,
    linkKeyType: 1,
    controllerName: 'DualSense Edge',
    vendorId: 0x054c,
    productId: 0x0df2,
    protocolVersion: '1.7.1'
  },
  firmwareLogDirectory: null,
  firmwareLogPath: null,
  firmwareLogEnabled: false,
  firmwareLogDroppedBytes: 0,
  firmwareLogLastError: null,
  audioDebugLogPath: null,
  audioDebugLogLines: [],
  audioDebugDroppedCount: 0,
  audioDebugStats: null,
  triggerTraceLines: [],
  triggerTraceDroppedCount: 0,
  feedbackTraceLines: [],
  feedbackTraceDroppedCount: 0,
  audioStatus: null
};

export function createDefaultSnapshot(overrides: Partial<BridgeSnapshot> = {}): BridgeSnapshot {
  return {
    state: 'connected',
    message: 'Bridge operational',
    status: {
      controllerConnected: true,
      controllerType: 'dualsense-edge',
      batteryPercent: 85,
      rawPowerState: 0,
      audioRecent: false,
      hapticsReady: true,
      hapticsGainPercent: 100,
      speakerVolumePercent: 100,
      speakerGainLevel: 4,
      lightbarColor: {
        red: 0,
        green: 102,
        blue: 255,
        brightnessPercent: 100
      },
      lightbarOverrideEnabled: false,
      micMuted: false,
      muteButtonMode: 'normal',
      muteKeyboardUsage: 0,
      muteKeyboardModifiers: 0,
      muteKeyboardBehavior: 'tap',
      muteKeyboardChordStarterEnabled: false,
      quietModeEnabled: false,
      hostPersonaMode: 'dualsense',
      audioDebug: {
        usbHostSpeakerVolumePercent: 100,
        usbHostMicVolumePercent: 100,
        usbHostSpeakerMute: false,
        usbHostMicMute: false,
        lastHostOutputLength: 0,
        lastHostOutputReportId: 0,
        lastHostOutputCount: 0
      },
      ledEnabled: true,
      idleDisconnectEnabled: false,
      idleDisconnectTimeoutMinutes: 15,
      signalStrengthDbm: null,
      usbSuspendDisconnectEnabled: true,
      sleepKeybindEnabled: false,
      wakeOnConnectEnabled: true,
      settingsRevision: 1,
      lastCommandResult: ACK_RESULT.OK,
      testHapticsBusy: false,
      testHapticsCooldown: false,
      hostOutputRecent: false,
      adaptiveTriggerOutputRecent: false,
      testAdaptiveTriggersBusy: false,
      uptimeSeconds: 3600,
      firmwareVersion: '1.7.1',
      firmwareFlags: {
        companion: true,
        dse: true,
        speakerVolumeControl: true,
        lightbarControl: true,
        lightbarOverrideControl: true,
        muteButtonActions: true,
        hapticsBufferLengthControl: true,
        adaptiveTriggersControl: true,
        usbSuspendDisconnectControl: true,
        sleepControllerControl: true,
        pollingRateControl: true,
        hostPersonaControl: true,
        audioReactiveHapticsControl: true,
        wakeOnConnectControl: true
      },
      supportedHostPersonaModes: ['dualsense', 'dualsense-edge', 'xbox', 'ds4'],
      protocolVersion: '1.7.1'
    },
    settings: { ...DEFAULT_MOCK_SETTINGS },
    diagnostics: { ...DEFAULT_MOCK_DIAGNOSTICS },
    personaTransition: null,
    bridgeDevices: {
      bridges: [
        {
          path: 'usb:mock-pico-01',
          containerId: 'bridge-container-01',
          selected: true,
          connected: true,
          uniqueId: 'pico-01',
          name: 'Pico DS5 Bridge'
        }
      ],
      directControllers: [],
      selectedBridgePath: 'usb:mock-pico-01'
    },
    stickInputPreview: null,
    activeGame: null,
    ...overrides
  };
}
